<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AssemblyConstituencySeeder extends Seeder
{
    public function run()
    {
        $items = [
            ['id' => 1, 'name' => 'Ichchapuram', 'loksabha_constituency_id' => 1, 'district_id' => 5420],
            ['id' => 2, 'name' => 'Palasa', 'loksabha_constituency_id' => 1, 'district_id' => 5420],
            ['id' => 3, 'name' => 'Tekkali', 'loksabha_constituency_id' => 1, 'district_id' => 5420],
            ['id' => 4, 'name' => 'Pathapatnam', 'loksabha_constituency_id' => 1, 'district_id' => 5420],
            ['id' => 5, 'name' => 'Srikakulam', 'loksabha_constituency_id' => 1, 'district_id' => 5420],
            ['id' => 6, 'name' => 'Amadalavalasa', 'loksabha_constituency_id' => 1, 'district_id' => 5420],
            ['id' => 7, 'name' => 'Etcherla', 'loksabha_constituency_id' => 2, 'district_id' => 5420],
            ['id' => 8, 'name' => 'Narasannapeta', 'loksabha_constituency_id' => 1, 'district_id' => 5420],
            ['id' => 9, 'name' => 'Rajam', 'loksabha_constituency_id' => 2, 'district_id' => 5431],
            ['id' => 10, 'name' => 'Palakonda', 'loksabha_constituency_id' => 3, 'district_id' => 5430],
            ['id' => 11, 'name' => 'Kurupam', 'loksabha_constituency_id' => 3, 'district_id' => 5430],
            ['id' => 12, 'name' => 'Parvathipuram', 'loksabha_constituency_id' => 3, 'district_id' => 5430],
            ['id' => 13, 'name' => 'Salur', 'loksabha_constituency_id' => 3, 'district_id' => 5430],
            ['id' => 14, 'name' => 'Bobbili', 'loksabha_constituency_id' => 2, 'district_id' => 5431],
            ['id' => 15, 'name' => 'Cheepurupalli', 'loksabha_constituency_id' => 2, 'district_id' => 5431],
            ['id' => 16, 'name' => 'Gajapathinagaram', 'loksabha_constituency_id' => 2, 'district_id' => 5431],
            ['id' => 17, 'name' => 'Nellimarla', 'loksabha_constituency_id' => 2, 'district_id' => 5431],
            ['id' => 18, 'name' => 'Vizianagaram', 'loksabha_constituency_id' => 2, 'district_id' => 5431],
            ['id' => 19, 'name' => 'Srungavarapukota', 'loksabha_constituency_id' => 4, 'district_id' => 5431],
            ['id' => 20, 'name' => 'Bhimili', 'loksabha_constituency_id' => 4, 'district_id' => 5442],
            ['id' => 21, 'name' => 'Visakhapatnam East', 'loksabha_constituency_id' => 4, 'district_id' => 5442],
            ['id' => 22, 'name' => 'Visakhapatnam South', 'loksabha_constituency_id' => 4, 'district_id' => 5442],
            ['id' => 23, 'name' => 'Visakhapatnam North', 'loksabha_constituency_id' => 4, 'district_id' => 5442],
            ['id' => 24, 'name' => 'Visakhapatnam West', 'loksabha_constituency_id' => 4, 'district_id' => 5442],
            ['id' => 25, 'name' => 'Gajuwaka', 'loksabha_constituency_id' => 4, 'district_id' => 5442],
            ['id' => 26, 'name' => 'Chodavaram', 'loksabha_constituency_id' => 5, 'district_id' => 5441],
            ['id' => 27, 'name' => 'Madugula', 'loksabha_constituency_id' => 5, 'district_id' => 5441],
            ['id' => 28, 'name' => 'Araku Valley', 'loksabha_constituency_id' => 3, 'district_id' => 5440],
            ['id' => 29, 'name' => 'Paderu', 'loksabha_constituency_id' => 3, 'district_id' => 5440],
            ['id' => 30, 'name' => 'Anakapalle', 'loksabha_constituency_id' => 5, 'district_id' => 5441],
            ['id' => 31, 'name' => 'Pendurthi', 'loksabha_constituency_id' => 5, 'district_id' => 5441],
            ['id' => 32, 'name' => 'Elamanchili', 'loksabha_constituency_id' => 5, 'district_id' => 5441],
            ['id' => 33, 'name' => 'Payakaraopet', 'loksabha_constituency_id' => 6, 'district_id' => 5441],
            ['id' => 34, 'name' => 'Narsipatnam', 'loksabha_constituency_id' => 6, 'district_id' => 5441],
            ['id' => 35, 'name' => 'Tuni', 'loksabha_constituency_id' => 6, 'district_id' => 5451],
            ['id' => 36, 'name' => 'Prathipadu (Kakinada)', 'loksabha_constituency_id' => 6, 'district_id' => 5451],
            ['id' => 37, 'name' => 'Pithapuram', 'loksabha_constituency_id' => 6, 'district_id' => 5451],
            ['id' => 38, 'name' => 'Kakinada Rural', 'loksabha_constituency_id' => 6, 'district_id' => 5451],
            ['id' => 39, 'name' => 'Peddapuram', 'loksabha_constituency_id' => 6, 'district_id' => 5451],
            ['id' => 40, 'name' => 'Anaparthy', 'loksabha_constituency_id' => 7, 'district_id' => 5450],
            ['id' => 41, 'name' => 'Kakinada City', 'loksabha_constituency_id' => 6, 'district_id' => 5451],
            ['id' => 42, 'name' => 'Ramachandrapuram', 'loksabha_constituency_id' => 8, 'district_id' => 5452],
            ['id' => 43, 'name' => 'Mummidivaram', 'loksabha_constituency_id' => 8, 'district_id' => 5452],
            ['id' => 44, 'name' => 'Amalapuram', 'loksabha_constituency_id' => 8, 'district_id' => 5452],
            ['id' => 45, 'name' => 'Razole', 'loksabha_constituency_id' => 8, 'district_id' => 5452],
            ['id' => 46, 'name' => 'Gannavaram (Konaseema)', 'loksabha_constituency_id' => 8, 'district_id' => 5452],
            ['id' => 47, 'name' => 'Kothapeta', 'loksabha_constituency_id' => 8, 'district_id' => 5452],
            ['id' => 48, 'name' => 'Mandapeta', 'loksabha_constituency_id' => 8, 'district_id' => 5452],
            ['id' => 49, 'name' => 'Rajanagaram', 'loksabha_constituency_id' => 7, 'district_id' => 5450],
            ['id' => 51, 'name' => 'Rajahmundry Rural', 'loksabha_constituency_id' => 7, 'district_id' => 5450],
            ['id' => 52, 'name' => 'Jaggampeta', 'loksabha_constituency_id' => 6, 'district_id' => 5451],
            ['id' => 53, 'name' => 'Rampachodavaram', 'loksabha_constituency_id' => 3, 'district_id' => 5440],
            ['id' => 54, 'name' => 'Kovvur', 'loksabha_constituency_id' => 7, 'district_id' => 5450],
            ['id' => 55, 'name' => 'Nidadavole', 'loksabha_constituency_id' => 7, 'district_id' => 5450],
            ['id' => 56, 'name' => 'Achanta', 'loksabha_constituency_id' => 9, 'district_id' => 5461],
            ['id' => 57, 'name' => 'Palakollu', 'loksabha_constituency_id' => 9, 'district_id' => 5461],
            ['id' => 58, 'name' => 'Narasapuram', 'loksabha_constituency_id' => 9, 'district_id' => 5461],
            ['id' => 59, 'name' => 'Bhimavaram', 'loksabha_constituency_id' => 9, 'district_id' => 5461],
            ['id' => 60, 'name' => 'Undi', 'loksabha_constituency_id' => 9, 'district_id' => 5461],
            ['id' => 61, 'name' => 'Tanuku', 'loksabha_constituency_id' => 9, 'district_id' => 5461],
            ['id' => 62, 'name' => 'Tadepalligudem', 'loksabha_constituency_id' => 9, 'district_id' => 5461],
            ['id' => 63, 'name' => 'Unguturu', 'loksabha_constituency_id' => 10, 'district_id' => 5460],
            ['id' => 64, 'name' => 'Denduluru', 'loksabha_constituency_id' => 10, 'district_id' => 5460],
            ['id' => 66, 'name' => 'Gopalapuram', 'loksabha_constituency_id' => 7, 'district_id' => 5450],
            ['id' => 67, 'name' => 'Polavaram', 'loksabha_constituency_id' => 10, 'district_id' => 5460],
            ['id' => 68, 'name' => 'Chintalapudi', 'loksabha_constituency_id' => 10, 'district_id' => 5460],
            ['id' => 69, 'name' => 'Tiruvuru', 'loksabha_constituency_id' => 11, 'district_id' => 5471],
            ['id' => 70, 'name' => 'Nuzvid', 'loksabha_constituency_id' => 10, 'district_id' => 5460],
            ['id' => 71, 'name' => 'Gannavaram (Krishna)', 'loksabha_constituency_id' => 12, 'district_id' => 5470],
            ['id' => 72, 'name' => 'Gudivada', 'loksabha_constituency_id' => 12, 'district_id' => 5470],
            ['id' => 73, 'name' => 'Kaikalur', 'loksabha_constituency_id' => 10, 'district_id' => 5460],
            ['id' => 74, 'name' => 'Pedana', 'loksabha_constituency_id' => 12, 'district_id' => 5470],
            ['id' => 75, 'name' => 'Machilipatnam', 'loksabha_constituency_id' => 12, 'district_id' => 5470],
            ['id' => 76, 'name' => 'Avanigadda', 'loksabha_constituency_id' => 12, 'district_id' => 5470],
            ['id' => 77, 'name' => 'Pamarru', 'loksabha_constituency_id' => 12, 'district_id' => 5470],
            ['id' => 78, 'name' => 'Penamaluru', 'loksabha_constituency_id' => 12, 'district_id' => 5470],
            ['id' => 79, 'name' => 'Vijayawada West', 'loksabha_constituency_id' => 11, 'district_id' => 5471],
            ['id' => 80, 'name' => 'Vijayawada Central', 'loksabha_constituency_id' => 11, 'district_id' => 5471],
            ['id' => 81, 'name' => 'Vijayawada East', 'loksabha_constituency_id' => 11, 'district_id' => 5471],
            ['id' => 82, 'name' => 'Mylavaram', 'loksabha_constituency_id' => 11, 'district_id' => 5471],
            ['id' => 83, 'name' => 'Nandigama', 'loksabha_constituency_id' => 11, 'district_id' => 5471],
            ['id' => 84, 'name' => 'Jaggayyapeta', 'loksabha_constituency_id' => 11, 'district_id' => 5471],
            ['id' => 85, 'name' => 'Pedakurapadu', 'loksabha_constituency_id' => 13, 'district_id' => 5481],
            ['id' => 86, 'name' => 'Tadikonda', 'loksabha_constituency_id' => 14, 'district_id' => 5480],
            ['id' => 87, 'name' => 'Mangalagiri', 'loksabha_constituency_id' => 14, 'district_id' => 5480],
            ['id' => 88, 'name' => 'Ponnuru', 'loksabha_constituency_id' => 14, 'district_id' => 5480],
            ['id' => 89, 'name' => 'Vemuru', 'loksabha_constituency_id' => 15, 'district_id' => 5490],
            ['id' => 90, 'name' => 'Repalle', 'loksabha_constituency_id' => 15, 'district_id' => 5490],
            ['id' => 91, 'name' => 'Tenali', 'loksabha_constituency_id' => 14, 'district_id' => 5480],
            ['id' => 92, 'name' => 'Bapatla', 'loksabha_constituency_id' => 15, 'district_id' => 5490],
            ['id' => 93, 'name' => 'Prathipadu (Guntur)', 'loksabha_constituency_id' => 14, 'district_id' => 5480],
            ['id' => 94, 'name' => 'Guntur West', 'loksabha_constituency_id' => 14, 'district_id' => 5480],
            ['id' => 95, 'name' => 'Guntur East', 'loksabha_constituency_id' => 14, 'district_id' => 5480],
            ['id' => 96, 'name' => 'Chilakaluripet', 'loksabha_constituency_id' => 13, 'district_id' => 5481],
            ['id' => 97, 'name' => 'Narasaraopet', 'loksabha_constituency_id' => 13, 'district_id' => 5481],
            ['id' => 98, 'name' => 'Sattenapalle', 'loksabha_constituency_id' => 13, 'district_id' => 5481],
            ['id' => 99, 'name' => 'Vinukonda', 'loksabha_constituency_id' => 13, 'district_id' => 5481],
            ['id' => 100, 'name' => 'Gurajala', 'loksabha_constituency_id' => 13, 'district_id' => 5481],
            ['id' => 101, 'name' => 'Macherla', 'loksabha_constituency_id' => 13, 'district_id' => 5481],
            ['id' => 102, 'name' => 'Yerragondapalem', 'loksabha_constituency_id' => 16, 'district_id' => 5491],
            ['id' => 103, 'name' => 'Darsi', 'loksabha_constituency_id' => 16, 'district_id' => 5491],
            ['id' => 104, 'name' => 'Parchur', 'loksabha_constituency_id' => 15, 'district_id' => 5490],
            ['id' => 105, 'name' => 'Addanki', 'loksabha_constituency_id' => 15, 'district_id' => 5490],
            ['id' => 106, 'name' => 'Chirala', 'loksabha_constituency_id' => 15, 'district_id' => 5490],
            ['id' => 107, 'name' => 'Santhanuthalapadu', 'loksabha_constituency_id' => 15, 'district_id' => 5491],
            ['id' => 108, 'name' => 'Ongole', 'loksabha_constituency_id' => 16, 'district_id' => 5491],
            ['id' => 109, 'name' => 'Kandukur', 'loksabha_constituency_id' => 17, 'district_id' => 5500],
            ['id' => 110, 'name' => 'Kondapi', 'loksabha_constituency_id' => 16, 'district_id' => 5491],
            ['id' => 111, 'name' => 'Markapuram', 'loksabha_constituency_id' => 16, 'district_id' => 5491],
            ['id' => 112, 'name' => 'Giddalur', 'loksabha_constituency_id' => 16, 'district_id' => 5491],
            ['id' => 113, 'name' => 'Kanigiri', 'loksabha_constituency_id' => 16, 'district_id' => 5491],
            ['id' => 114, 'name' => 'Kavali', 'loksabha_constituency_id' => 17, 'district_id' => 5500],
            ['id' => 115, 'name' => 'Atmakur', 'loksabha_constituency_id' => 17, 'district_id' => 5500],
            ['id' => 116, 'name' => 'Kovur', 'loksabha_constituency_id' => 17, 'district_id' => 5500],
            ['id' => 117, 'name' => 'Nellore City', 'loksabha_constituency_id' => 17, 'district_id' => 5500],
            ['id' => 118, 'name' => 'Nellore Rural', 'loksabha_constituency_id' => 17, 'district_id' => 5500],
            ['id' => 119, 'name' => 'Sarvepalli', 'loksabha_constituency_id' => 18, 'district_id' => 5500],
            ['id' => 120, 'name' => 'Gudur', 'loksabha_constituency_id' => 18, 'district_id' => 5542],
            ['id' => 121, 'name' => 'Sullurpeta', 'loksabha_constituency_id' => 18, 'district_id' => 5542],
            ['id' => 122, 'name' => 'Venkatagiri', 'loksabha_constituency_id' => 18, 'district_id' => 5542],
            ['id' => 123, 'name' => 'Udayagiri', 'loksabha_constituency_id' => 17, 'district_id' => 5500],
            ['id' => 124, 'name' => 'Badvel', 'loksabha_constituency_id' => 19, 'district_id' => 5510],
            ['id' => 125, 'name' => 'Rajampet', 'loksabha_constituency_id' => 20, 'district_id' => 5540],
            ['id' => 126, 'name' => 'Kadapa', 'loksabha_constituency_id' => 19, 'district_id' => 5510],
            ['id' => 127, 'name' => 'Kodur', 'loksabha_constituency_id' => 20, 'district_id' => 5540],
            ['id' => 128, 'name' => 'Rayachoti', 'loksabha_constituency_id' => 20, 'district_id' => 5540],
            ['id' => 129, 'name' => 'Pulivendla', 'loksabha_constituency_id' => 19, 'district_id' => 5510],
            ['id' => 130, 'name' => 'Kamalapuram', 'loksabha_constituency_id' => 19, 'district_id' => 5510],
            ['id' => 131, 'name' => 'Jammalamadugu', 'loksabha_constituency_id' => 19, 'district_id' => 5510],
            ['id' => 132, 'name' => 'Proddatur', 'loksabha_constituency_id' => 19, 'district_id' => 5510],
            ['id' => 133, 'name' => 'Mydukur', 'loksabha_constituency_id' => 19, 'district_id' => 5510],
            ['id' => 134, 'name' => 'Allagadda', 'loksabha_constituency_id' => 21, 'district_id' => 5521],
            ['id' => 135, 'name' => 'Srisailam', 'loksabha_constituency_id' => 21, 'district_id' => 5521],
            ['id' => 136, 'name' => 'Nandikotkur', 'loksabha_constituency_id' => 21, 'district_id' => 5521],
            ['id' => 137, 'name' => 'Kurnool', 'loksabha_constituency_id' => 22, 'district_id' => 5520],
            ['id' => 138, 'name' => 'Panyam', 'loksabha_constituency_id' => 21, 'district_id' => 5521],
            ['id' => 139, 'name' => 'Nandyal', 'loksabha_constituency_id' => 21, 'district_id' => 5521],
            ['id' => 140, 'name' => 'Banaganapalle', 'loksabha_constituency_id' => 21, 'district_id' => 5521],
            ['id' => 141, 'name' => 'Dhone', 'loksabha_constituency_id' => 21, 'district_id' => 5521],
            ['id' => 142, 'name' => 'Pattikonda', 'loksabha_constituency_id' => 22, 'district_id' => 5520],
            ['id' => 143, 'name' => 'Kodumur', 'loksabha_constituency_id' => 22, 'district_id' => 5520],
            ['id' => 144, 'name' => 'Yemmiganur', 'loksabha_constituency_id' => 22, 'district_id' => 5520],
            ['id' => 145, 'name' => 'Mantralayam', 'loksabha_constituency_id' => 22, 'district_id' => 5520],
            ['id' => 146, 'name' => 'Adoni', 'loksabha_constituency_id' => 22, 'district_id' => 5520],
            ['id' => 147, 'name' => 'Alur', 'loksabha_constituency_id' => 22, 'district_id' => 5520],
            ['id' => 148, 'name' => 'Rayadurg', 'loksabha_constituency_id' => 23, 'district_id' => 5530],
            ['id' => 149, 'name' => 'Uravakonda', 'loksabha_constituency_id' => 23, 'district_id' => 5530],
            ['id' => 150, 'name' => 'Guntakal', 'loksabha_constituency_id' => 23, 'district_id' => 5530],
            ['id' => 151, 'name' => 'Tadipatri', 'loksabha_constituency_id' => 23, 'district_id' => 5530],
            ['id' => 152, 'name' => 'Singanamala', 'loksabha_constituency_id' => 23, 'district_id' => 5530],
            ['id' => 153, 'name' => 'Anantapur Urban', 'loksabha_constituency_id' => 23, 'district_id' => 5530],
            ['id' => 154, 'name' => 'Kalyandurg', 'loksabha_constituency_id' => 23, 'district_id' => 5530],
            ['id' => 155, 'name' => 'Raptadu', 'loksabha_constituency_id' => 24, 'district_id' => 5530],
            ['id' => 156, 'name' => 'Madakasira', 'loksabha_constituency_id' => 24, 'district_id' => 5531],
            ['id' => 157, 'name' => 'Hindupur', 'loksabha_constituency_id' => 24, 'district_id' => 5531],
            ['id' => 158, 'name' => 'Penukonda', 'loksabha_constituency_id' => 24, 'district_id' => 5531],
            ['id' => 159, 'name' => 'Puttaparthi', 'loksabha_constituency_id' => 24, 'district_id' => 5531],
            ['id' => 160, 'name' => 'Dharmavaram', 'loksabha_constituency_id' => 24, 'district_id' => 5531],
            ['id' => 161, 'name' => 'Kadiri', 'loksabha_constituency_id' => 24, 'district_id' => 5531],
            ['id' => 162, 'name' => 'Thamballapalle', 'loksabha_constituency_id' => 20, 'district_id' => 5540],
            ['id' => 163, 'name' => 'Pileru', 'loksabha_constituency_id' => 20, 'district_id' => 5540],
            ['id' => 164, 'name' => 'Madanapalle', 'loksabha_constituency_id' => 20, 'district_id' => 5540],
            ['id' => 165, 'name' => 'Punganur', 'loksabha_constituency_id' => 20, 'district_id' => 5541],
            ['id' => 166, 'name' => 'Chandragiri', 'loksabha_constituency_id' => 25, 'district_id' => 5542],
            ['id' => 167, 'name' => 'Tirupati', 'loksabha_constituency_id' => 18, 'district_id' => 5542],
            ['id' => 168, 'name' => 'Srikalahasti', 'loksabha_constituency_id' => 18, 'district_id' => 5542],
            ['id' => 169, 'name' => 'Sathyavedu', 'loksabha_constituency_id' => 18, 'district_id' => 5542],
            ['id' => 171, 'name' => 'Gangadhara Nellore', 'loksabha_constituency_id' => 25, 'district_id' => 5541],
            ['id' => 172, 'name' => 'Chittoor', 'loksabha_constituency_id' => 25, 'district_id' => 5541],
            ['id' => 173, 'name' => 'Puthalapattu', 'loksabha_constituency_id' => 25, 'district_id' => 5541],
            ['id' => 174, 'name' => 'Palamaner', 'loksabha_constituency_id' => 25, 'district_id' => 5541],
            ['id' => 175, 'name' => 'Kuppam', 'loksabha_constituency_id' => 25, 'district_id' => 5541],
            ['id' => 1701, 'name' => 'Nagari-Cittoor Part', 'loksabha_constituency_id' => 25, 'district_id' => 5541],
            ['id' => 1702, 'name' => 'Nagari-Tirupati Part', 'loksabha_constituency_id' => 25, 'district_id' => 5542],
        ];
foreach ($items as $item) {
    \App\Models\PlaceRelated\AssemblyConstituency::create($item);
}  
    }
}
